# For more info on HTTP files go to https://aka.ms/vs/httpfile

@host  = https://localhost:7112

POST {{host}}/api/orders
Content-Type: application/json

{
  "orderId": "abc123",
  "customerId": "12345",
  "amount": 99.99
} 